check for success before snapshot restore
## Description 

It's happened a few times where users try to restore a snapshot that
hasn't been uploaded yet or does not exist, this will cleanly exit in
the case that the success marker hasn't been uploaded.

## Test Plan 

tested locally:
```
$ target/debug/haneul-tool download-db-snapshot --epoch "439" --genesis "/opt/haneul/config/genesis.blob" --formal --network mainnet --path /opt/haneul/db/authorities_db --num-parallel-downloads 50 --snapshot-bucket-type=gcs

thread 'main' panicked at /Users/jeong-gh/src/github.com/johnjmartin/haneul/crates/haneul-tool/src/commands.rs:714:21:
Aborting snapshot restore: missing success marker at haneullabs-mainnet-formal/epoch_439/_SUCCESS
```
---
If your changes are not user-facing and not a breaking change, you can
skip the following section. Otherwise, please indicate what changed, and
then add to the Release Notes section as highlighted during the release
process.

### Type of Change (Check all that apply)

- [ ] protocol change
- [ ] user-visible impact
- [ ] breaking change for a client SDKs
- [ ] breaking change for FNs (FN binary must upgrade)
- [ ] breaking change for validators or node operators (must upgrade
binaries)
- [ ] breaking change for on-chain data layout
- [ ] necessitate either a data wipe or data migration

### Release notes