Adds configuration for playtron provider in Devnet
## Description 

Adds playtron provides to Devnet. 
Afaik, since Playtron serves only the `authorization_code` flow it
cannot work with the current version of the keytool, so no need to bump
fastcrypto version here, unless I am missing anything.
(Related:
https://github.com/GeunhwaJeong/fastcrypto/blob/781398d38fbf342a50e66dc0ad11d6227839bd68/fastcrypto-zkp/src/bn254/utils.rs#L88)
If I do miss something though, it looks that bumping to a later
fastcrypto revision it causes dependency related error during the test
execution (`cargo test -p haneul-swarm-config`). Like the following:
```
error[E0433]: failed to resolve: could not find `conversions` in `bls12381`
   --> haneul-execution/v1/haneul-move-natives/src/crypto/groth16.rs:205:41
    |
205 |             > fastcrypto_zkp::bls12381::conversions::SCALAR_SIZE * MAX_PUBLIC_INPUTS
    |  
```
 
 
 
## Test plan 
running localnet with 
```
cargo build --bin haneul 
RUST_LOG=info target/debug/haneul start --force-regenesis --with-faucet
```

and grep logs for JWK pulling for playtron and threedos ok. 

```
2024-09-11T14:51:07.219647Z  INFO node{name=k#b3fd5efb..}:jwk_updater_task{epoch=0}: haneul_node: Submitting JWK to consensus: JwkId { iss: "https://oauth2.playtron.one", kid: "1fd66a18-7afd-4086-ba57-a8ca9b398406" }
2024-09-11T14:51:07.219736Z  INFO node{name=k#b3fd5efb..}:jwk_updater_task{epoch=0}: haneul_node: Submitting JWK to consensus: JwkId { iss: "https://oauth2.playtron.one", kid: "7388b63c-ba03-4fe3-85e3-6717f91d55b1" }
2024-09-11T14:51:07.219789Z  INFO node{name=k#b3fd5efb..}:jwk_updater_task{epoch=0}: haneul_node: Submitting JWK to consensus: JwkId { iss: "https://oauth2.playtron.one", kid: "e55421cb-cdbd-4791-a590-ad8ca798aa89" }
```

for threedos: 
```
2024-09-11T14:52:08.492045Z  INFO node{name=kdcff6d1..}: haneul_core::authority::authority_per_epoch_store: received jwk vote from kdcff6d1.. for jwk (JwkId { iss: "https://auth.3dos.io", kid: "6d361dc9637a275eb585a915af26198ff0d97326ca13f4baf0e4805f72f2a9a0" }, JWK { kty: "RSA", e: "AQAB", n: "y_8hHwq7w2yE4968sbQF98iGUhnu0BwyB5khTxVPAcUnMCYdp61zYcRWml2zdY4HAfq-Nnjb_pAli6I66Vpe9IE8Gf8uGRB0oYIo2S6tYMEe0lhRaEDYVbMdQkuKxTIYMNBXSd_kCHKJM1ZUAo7uFoq_bWuzt2hRG2-79z-Ycbiw0wil0rzFHlpNBKsBLKM4GSGUwOejaL2zCiE_rjf77AvOaJLRd4I_DBYG16t8D1BkxbhkcQCmOxYGG0NqjP3z0lz-w1ALqHCNfhzczZOsgaCrbSlcTKcBTq1syAUUhQmounW7nG5clBIfPQRVH7jCoPztiJUZg6Xz1AN6V07xnw", alg: "RS256" })
2024-09-11T14:52:08.492281Z  INFO node{name=kdcff6d1..}: haneul_core::authority::authority_per_epoch_store: received jwk vote from kf25ef6.. for jwk (JwkId { iss: "https://auth.3dos.io", kid: "6d361dc9637a275eb585a915af26198ff0d97326ca13f4baf0e4805f72f2a9a0" }, JWK { kty: "RSA", e: "AQAB", n: "y_8hHwq7w2yE4968sbQF98iGUhnu0BwyB5khTxVPAcUnMCYdp61zYcRWml2zdY4HAfq-Nnjb_pAli6I66Vpe9IE8Gf8uGRB0oYIo2S6tYMEe0lhRaEDYVbMdQkuKxTIYMNBXSd_kCHKJM1ZUAo7uFoq_bWuzt2hRG2-79z-Ycbiw0wil0rzFHlpNBKsBLKM4GSGUwOejaL2zCiE_rjf77AvOaJLRd4I_DBYG16t8D1BkxbhkcQCmOxYGG0NqjP3z0lz-w1ALqHCNfhzczZOsgaCrbSlcTKcBTq1syAUUhQmounW7nG5clBIfPQRVH7jCoPztiJUZg6Xz1AN6V07xnw", alg: "RS256" })
2024-09-11T14:52:08.492310Z  INFO node{name=kdcff6d1..}: haneul_core::authority::authority_per_epoch_store: jwk became active epoch=1 round=16 jwk=(JwkId { iss: "https://auth.3dos.io", kid: "6d361dc9637a275eb585a915af26198ff0d97326ca13f4baf0e4805f72f2a9a0" }, JWK { kty: "RSA", e: "AQAB", n: "y_8hHwq7w2yE4968sbQF98iGUhnu0BwyB5khTxVPAcUnMCYdp61zYcRWml2zdY4HAfq-Nnjb_pAli6I66Vpe9IE8Gf8uGRB0oYIo2S6tYMEe0lhRaEDYVbMdQkuKxTIYMNBXSd_kCHKJM1ZUAo7uFoq_bWuzt2hRG2-79z-Ycbiw0wil0rzFHlpNBKsBLKM4GSGUwOejaL2zCiE_rjf77AvOaJLRd4I_DBYG16t8D1BkxbhkcQCmOxYGG0NqjP3z0lz-w1ALqHCNfhzczZOsgaCrbSlcTKcBTq1syAUUhQmounW7nG5clBIfPQRVH7jCoPztiJUZg6Xz1AN6V07xnw", alg: "RS256" })
2024-09-11T14:52:08.492464Z  INFO node{name=kdcff6d1..}: haneul_core::authority::authority_per_epoch_store: received jwk vote from k#b3fd5efb.. for jwk (JwkId { iss: "https://auth.3dos.io", kid: "6d361dc9637a275eb585a915af26198ff0d97326ca13f4baf0e4805f72f2a9a0" }, JWK { kty: "RSA", e: "AQAB", n: "y_8hHwq7w2yE4968sbQF98iGUhnu0BwyB5khTxVPAcUnMCYdp61zYcRWml2zdY4HAfq-Nnjb_pAli6I66Vpe9IE8Gf8uGRB0oYIo2S6tYMEe0lhRaEDYVbMdQkuKxTIYMNBXSd_kCHKJM1ZUAo7uFoq_bWuzt2hRG2-79z-Ycbiw0wil0rzFHlpNBKsBLKM4GSGUwOejaL2zCiE_rjf77AvOaJLRd4I_DBYG16t8D1BkxbhkcQCmOxYGG0NqjP3z0lz-w1ALqHCNfhzczZOsgaCrbSlcTKcBTq1syAUUhQmounW7nG5clBIfPQRVH7jCoPztiJUZg6Xz1AN6V07xnw", alg: "RS256" })
```
```
```
---

## Release notes

Check each box that your changes affect. If none of the boxes relate to
your changes, release notes aren't required.

For each box you select, include information after the relevant heading
that describes the impact of your changes that a user might notice and
any actions they must take to implement updates.

- [ ] Protocol: 
- [ ] Nodes (Validators and Full nodes): 
- [ ] Indexer: 
- [ ] JSON-RPC: 
- [ ] GraphQL: 
- [ ] CLI: 
- [ ] Rust SDK:
- [ ] REST API:

---------