examples: fix custom indexer
## Description 

The custom indexer example is broken:
```
error[E0195]: lifetime parameters or bounds on method `process_checkpoint` do not match the trait declaration
  --> remote_reader.rs:14:14
   |
14 |     async fn process_checkpoint(&self, checkpoint: CheckpointData) -> Result<()> {
   |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ lifetimes do not match method in trait
```
This PR fixes it. 


## Test plan 

```
cd examples/custom-indexer/rust
cargo run  --bin local_reader --release
cargo run  --bin remote_reader --release
```

---

## Release notes

Check each box that your changes affect. If none of the boxes relate to
your changes, release notes aren't required.

For each box you select, include information after the relevant heading
that describes the impact of your changes that a user might notice and
any actions they must take to implement updates.

- [ ] Protocol: 
- [ ] Nodes (Validators and Full nodes): 
- [ ] Indexer: 
- [ ] JSON-RPC: 
- [ ] GraphQL: 
- [ ] CLI: 
- [ ] Rust SDK:
- [ ] REST API: