[ts-sdk] websocket client reconnect should delete existing subscription
## Description 
The `websocket-client.ts` has a memory leak in the reconnect logic.
The subscriptions map uses the request id as the map key. At reconnect,
wsclient loops through the map’s values and resubscribe them. The
`input.id` is set as the key (Line 121) as it's defined, but the id in
the value object is a new request id. The next reconnect will set the
last request id with a duplicated subscription object. Causing the map
size increment in Fibonacci at every reconnect. That’s probably the
cause we are seeing JSONRPCError: Too many subscriptions on the
connection.

It can be fixed by always deleting existing input.id key in the
subscriptions map then setting the new requested id as key.

To reproduce on local, I put some loggings to examine the subscriptions
map size after every reconnect:
```
Disconnects ++
Subscriptions map size: 1
Disconnects ++
Subscriptions map size: 2
Disconnects ++
Subscriptions map size: 3
Disconnects ++
Subscriptions map size: 5
Disconnects ++
Subscriptions map size: 8
...
...
Disconnects ++
Subscriptions map size: 987
Disconnects ++
Subscriptions map size: 1597

JSONRPCError: Too many subscriptions on the connection
```

## Test Plan 

How did you test the new or updated feature?
Applied the change as a patch in our service, I could see the reconnect
logic work fine and no `JSONRPCError: Too many subscriptions on the
connection` error was seen. The test was done on testnet.

---
If your changes are not user-facing and not a breaking change, you can
skip the following section. Otherwise, please indicate what changed, and
then add to the Release Notes section as highlighted during the release
process.

### Type of Change (Check all that apply)

- [ ] protocol change
- [ ] user-visible impact
- [ ] breaking change for a client SDKs
- [ ] breaking change for FNs (FN binary must upgrade)
- [ ] breaking change for validators or node operators (must upgrade
binaries)
- [ ] breaking change for on-chain data layout
- [ ] necessitate either a data wipe or data migration

### Release notes

---------