haneul branch cut: generate all required PRs
## Description 
Generates framework bytecode snapshot and version bump PRs

## Test plan 
Test Plan:
Two PRs were generated with the shell script:
https://github.com/GeunhwaJeong/haneul/pull/23286 and
https://github.com/GeunhwaJeong/haneul/pull/23287

```
eugene@eugene-dev ~/code/haneul/ (ebmifa/gen_branch_cut_prs) $ ./scripts/gen_branch_cut_prs.sh 
Switched to a new branch 'eugene/haneul-v1.56.0-bytecode-framework-snapshot-20250825164809'
   Compiling haneul-framework-snapshot v1.56.0 (/home/eugene/code/haneul/crates/haneul-framework-snapshot)
    Finished `dev` profile [unoptimized + debuginfo] target(s) in 8.01s
     Running `target/debug/haneul-framework-snapshot`
Staging all changed files...
[eugene/haneul-v1.56.0-bytecode-framework-snapshot-20250825164809 f8d3f845c9] Haneul v1.56.0 Framework Bytecode snapshot
 6 files changed, 30 insertions(+)
 create mode 100644 crates/haneul-framework-snapshot/bytecode_snapshot/95/0x0000000000000000000000000000000000000000000000000000000000000001
 create mode 100644 crates/haneul-framework-snapshot/bytecode_snapshot/95/0x0000000000000000000000000000000000000000000000000000000000000002
 create mode 100644 crates/haneul-framework-snapshot/bytecode_snapshot/95/0x0000000000000000000000000000000000000000000000000000000000000003
 create mode 100644 crates/haneul-framework-snapshot/bytecode_snapshot/95/0x000000000000000000000000000000000000000000000000000000000000000b
 create mode 100644 crates/haneul-framework-snapshot/bytecode_snapshot/95/0x000000000000000000000000000000000000000000000000000000000000dee9
Enumerating objects: 30, done.
Counting objects: 100% (30/30), done.
Delta compression using up to 16 threads
Compressing objects: 100% (24/24), done.
Writing objects: 100% (24/24), 81.22 KiB | 13.54 MiB/s, done.
Total 24 (delta 15), reused 0 (delta 0), pack-reused 0
remote: Resolving deltas: 100% (15/15), completed with 6 local objects.
remote: 
remote: Create a pull request for 'eugene/haneul-v1.56.0-bytecode-framework-snapshot-20250825164809' on GitHub by visiting:
remote:      https://github.com/GeunhwaJeong/haneul/pull/new/eugene/haneul-v1.56.0-bytecode-framework-snapshot-20250825164809
remote: 
remote: GitHub found 73 vulnerabilities on HaneulLabs/haneul's default branch (5 critical, 11 high, 46 moderate, 11 low). To find out more, visit:
remote:      https://github.com/GeunhwaJeong/haneul/security/dependabot
remote: 
To github.com:HaneulLabs/haneul.git
 * [new branch]            eugene/haneul-v1.56.0-bytecode-framework-snapshot-20250825164809 -> eugene/haneul-v1.56.0-bytecode-framework-snapshot-20250825164809
Branch 'eugene/haneul-v1.56.0-bytecode-framework-snapshot-20250825164809' set up to track remote branch 'eugene/haneul-v1.56.0-bytecode-framework-snapshot-20250825164809' from 'origin'.
Pull request for Haneul v1.56.0 Framework Bytecode snapshot created: https://github.com/GeunhwaJeong/haneul/pull/23286
✓ Pull request HaneulLabs/haneul will be automatically merged via squash when all requirements are met
Switched to branch 'main'
Your branch is up to date with 'origin/main'.
From github.com:HaneulLabs/haneul
 * branch                  main       -> FETCH_HEAD
Already up to date.
Switched to a new branch 'eugene/haneul-v1.57.0-version-bump-20250825164809'
    Updating crates.io index
    Checking haneul-sdk v1.57.0 (/home/eugene/code/haneul/crates/haneul-sdk)
    Checking haneul-move-natives-latest v0.1.0 (/home/eugene/code/haneul/haneul-execution/latest/haneul-move-natives)
    Checking haneul-data-ingestion-core v0.1.0 (/home/eugene/code/haneul/crates/haneul-data-ingestion-core)
   Compiling haneul-package-management v1.57.0 (/home/eugene/code/haneul/crates/haneul-package-management)
    Checking haneul-indexer-alt-framework v1.57.0 (/home/eugene/code/haneul/crates/haneul-indexer-alt-framework)
    Checking haneul-proxy v0.0.2 (/home/eugene/code/haneul/crates/haneul-proxy)
    Checking haneul-framework-snapshot v1.57.0 (/home/eugene/code/haneul/crates/haneul-framework-snapshot)
    Checking haneul-storage v0.1.0 (/home/eugene/code/haneul/crates/haneul-storage)
error[E0433]: failed to resolve: could not find `IdGasParameters` in `type_name`
   --> haneul-execution/latest/haneul-move-natives/src/lib.rs:849:33
    |
849 |             id: MSN::type_name::IdGasParameters::new(
    |                                 ^^^^^^^^^^^^^^^
    |                                 |
    |                                 could not find `IdGasParameters` in `type_name`
    |                                 help: a struct with a similar name exists: `GasParameters`

error[E0560]: struct `move_stdlib_natives::type_name::GasParameters` has no field named `id`
   --> haneul-execution/latest/haneul-move-natives/src/lib.rs:849:13
    |
849 |             id: MSN::type_name::IdGasParameters::new(
    |             ^^ `move_stdlib_natives::type_name::GasParameters` does not have this field
    |
    = note: all struct fields are already assigned

    Checking haneul-kvstore v1.57.0 (/home/eugene/code/haneul/crates/haneul-kvstore)
    Checking haneulns-indexer v1.57.0 (/home/eugene/code/haneul/crates/haneulns-indexer)
    Checking haneul-indexer-builder v0.1.0 (/home/eugene/code/haneul/crates/haneul-indexer-builder)
    Checking haneul-faucet v1.57.0 (/home/eugene/code/haneul/crates/haneul-faucet)
    Checking haneul-oracle v1.57.0 (/home/eugene/code/haneul/crates/haneul-oracle)
    Checking haneul-light-client v1.57.0 (/home/eugene/code/haneul/crates/haneul-light-client)
    Checking haneul-rpc-loadgen v1.57.0 (/home/eugene/code/haneul/crates/haneul-rpc-loadgen)
Some errors have detailed explanations: E0433, E0560.
For more information about an error, try `rustc --explain E0433`.
error: could not compile `haneul-move-natives-latest` (lib) due to 2 previous errors
warning: build failed, waiting for other jobs to finish...
Staging all changed files...
[eugene/haneul-v1.57.0-version-bump-20250825164809 f26604b6e2] Haneul v1.57.0 Version Bump
 3 files changed, 58 insertions(+), 58 deletions(-)
Enumerating objects: 15, done.
Counting objects: 100% (15/15), done.
Delta compression using up to 16 threads
Compressing objects: 100% (7/7), done.
Writing objects: 100% (8/8), 1.41 KiB | 361.00 KiB/s, done.
Total 8 (delta 5), reused 0 (delta 0), pack-reused 0
remote: Resolving deltas: 100% (5/5), completed with 5 local objects.
remote: 
remote: Create a pull request for 'eugene/haneul-v1.57.0-version-bump-20250825164809' on GitHub by visiting:
remote:      https://github.com/GeunhwaJeong/haneul/pull/new/eugene/haneul-v1.57.0-version-bump-20250825164809
remote: 
remote: GitHub found 73 vulnerabilities on HaneulLabs/haneul's default branch (5 critical, 11 high, 46 moderate, 11 low). To find out more, visit:
remote:      https://github.com/GeunhwaJeong/haneul/security/dependabot
remote: 
To github.com:HaneulLabs/haneul.git
 * [new branch]            eugene/haneul-v1.57.0-version-bump-20250825164809 -> eugene/haneul-v1.57.0-version-bump-20250825164809
Branch 'eugene/haneul-v1.57.0-version-bump-20250825164809' set up to track remote branch 'eugene/haneul-v1.57.0-version-bump-20250825164809' from 'origin'.
Pull request for Haneul v1.57.0 Version Bump created: https://github.com/GeunhwaJeong/haneul/pull/23287
```

---------