[StateAccumulator] Fix checkpoint accumulator idempotency bug
## Description 

Currently checkpoint accumulation is idempotent, therefore first to
write wins. This is an issue, however, given that we have two callsites
for checkpoint accumulation - checkpoint executor and checkpoint
builder, the latter of which calls accumulation for proposals that have
not yet made it through consensus, and therefore may not make it on
chain. The below test creates a scenario where a validator, due to
untimely crashes, proposes an empty checkpoint, and due to idempotency,
locally accumulates this empty checkpoint. Later, the network certifies
a checkpoint, but the call to accumulate it from checkpoint executor on
the errant node is ignored, causing inconsistency.

The fix is to remove idempotency. 

Repro against commit `a42f67c687` in `mlogan-dario-gas` branch:

```
MSIM_TEST_SEED=9920 RUST_LOG=haneul=debug,error cargo simtest test_simulated_load_reconfig_crashes -E '(test(test_simulated_load_reconfig_crashes) and !(test(test_simulated_load_reconfig_crashes_during_epoch_change)))'
```

Crashes with:

```
thread '<unnamed>' panicked at 'Inconsistent state detected: root state hash: ECMHLiveObjectSetDigest { digest: 20V+2YIdMmOUm/3e75tXD35YG55eCECG+0QzhK5Nb6g= }, live object set hash: ECMHLiveObjectSetDigest { digest: z73BdEzrUyr9/TwfjX6aSg/Viw8lCG7uN96/9rRhBss= }', crates/haneul-node/src/lib.rs:1077:13
```

## Test Plan 

```
for f in `seq 1 20`; do RUST_LOG=haneul=debug,error MSIM_TEST_SEED=9$f cargo simtest test_simulated_load_reconfig_crashes -E '(test(test_simulated_load_reconfig_crashes) and !(test(test_simulated_load_reconfig_crashes_during_epoch_change)))' --no-capture > test_$f 2>&1 &; done

----

for f in `seq 1 20`; do RUST_LOG=haneul=debug,error MSIM_TEST_SEED=99$f cargo simtest test_simulated_load_reconfig_crashes -E '(test(test_simulated_load_reconfig_crashes) and !(test(test_simulated_load_reconfig_crashes_during_epoch_change)))' --no-capture > test_$f 2>&1 &; done

```

---
If your changes are not user-facing and not a breaking change, you can
skip the following section. Otherwise, please indicate what changed, and
then add to the Release Notes section as highlighted during the release
process.

### Type of Change (Check all that apply)

- [ ] user-visible impact
- [ ] breaking change for a client SDKs
- [ ] breaking change for FNs (FN binary must upgrade)
- [ ] breaking change for validators or node operators (must upgrade
binaries)
- [ ] breaking change for on-chain data layout
- [ ] necessitate either a data wipe or data migration

### Release notes