[hardening] enforce enum order for `ExecutionFailureStatus` for SDK backward compat
## Description 

For some enums we require that variants are appended to the end of an
enum to ensure backward compat for SDK etc.
We currently use comments like
[this](https://github.com/GeunhwaJeong/haneul/blob/23dec3b234786f15a047d0820ce30e3477b05f0a/crates/haneul-types/src/execution_status.rs#L180-L181)
```
    // NOTE: if you want to add a new enum,
    // please add it at the end for Rust SDK backward compatibility.
```
 to inform folks to append but we dont actually enforce it.

This PR adds enforcement test on `ExecutionFailureStatus` and will add
for other types as I discover them.
Example test failure from swapping variants
```
panicked at 'Enum variant HaneulMoveVerificationTimedout has been swapped with HaneulMoveVerificationTimedoutNew at position 30. Not allowed: enum must be backward compatible.', crates/haneul-types/src/execution_status.rs:380:17
```



## Test Plan 

Manual testing of adding, swapping, removing variants.

---
If your changes are not user-facing and not a breaking change, you can
skip the following section. Otherwise, please indicate what changed, and
then add to the Release Notes section as highlighted during the release
process.

### Type of Change (Check all that apply)

- [ ] user-visible impact
- [ ] breaking change for a client SDKs
- [ ] breaking change for FNs (FN binary must upgrade)
- [ ] breaking change for validators or node operators (must upgrade
binaries)
- [ ] breaking change for on-chain data layout
- [ ] necessitate either a data wipe or data migration

### Release notes