[fix] narwhal synchronizer to gc certificates up to gc_round
## Description 

We have observed simtest failures with messages like:

```
2023-09-12T06:16:20.2666876Z [31;1m--- [0m[31;1mSTDERR:              [0m[35;1mhaneul-e2e-tests::reconfiguration_tests[0m [34;1mtest_reconfig_with_failing_validator[0m[31;1m ---[0m
2023-09-12T06:16:20.2667858Z thread '<unnamed>' panicked at 'Parent kXWcgU8cKSUnG1gL5MAjirFbd/pdLhfgpLDMsFOtTHk= not found for HFG7pP2s799ogJy1: C2(3, HFG7pP2s799ogJy1, E1)!', narwhal/primary/src/synchronizer.rs:163:21
2023-09-12T06:16:20.2668367Z stack backtrace:
2023-09-12T06:16:20.2668639Z    0: rust_begin_unwind
2023-09-12T06:16:20.2669009Z              at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/panicking.rs:578:5
2023-09-12T06:16:20.2669710Z    1: core::panicking::panic_fmt
2023-09-12T06:16:20.2670103Z              at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/core/src/panicking.rs:67:14
2023-09-12T06:16:20.2670584Z    2: narwhal_primary::synchronizer::Inner::accept_certificate_internal::{{closure}}::{{closure}}
2023-09-12T06:16:20.2671045Z              at /home/runner/work/haneul/haneul/narwhal/primary/src/synchronizer.rs:163:21
2023-09-12T06:16:20.2671793Z    3: narwhal_primary::synchronizer::Inner::accept_certificate_internal::{{closure}}
2023-09-12T06:16:20.2672276Z              at /home/runner/work/haneul/haneul/narwhal/primary/src/synchronizer.rs:143:5
2023-09-12T06:16:20.2672774Z    4: narwhal_primary::synchronizer::Inner::accept_suspended_certificate::{{closure}}
2023-09-12T06:16:20.2673273Z              at /home/runner/work/haneul/haneul/narwhal/primary/src/synchronizer.rs:131:13
2023-09-12T06:16:20.2673760Z    5: narwhal_primary::synchronizer::Synchronizer::new::{{closure}}::{{closure}}
2023-09-12T06:16:20.2674191Z              at /home/runner/work/haneul/haneul/narwhal/primary/src/synchronizer.rs:439:88
2023-09-12T06:16:20.2674626Z    6: narwhal_primary::synchronizer::Synchronizer::new::{{closure}}
2023-09-12T06:16:20.2675105Z              at /home/runner/work/haneul/haneul/narwhal/primary/src/synchronizer.rs:449:14
2023-09-12T06:16:20.2675545Z    7: <core::pin::Pin<P> as core::future::future::Future>::poll
2023-09-12T06:16:20.2675992Z              at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/core/src/future/future.rs:125:9
2023-09-12T06:16:20.2676460Z    8: <&mut F as core::future::future::Future>::poll
2023-09-12T06:16:20.2676906Z              at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/core/src/future/future.rs:113:9
2023-09-12T06:16:20.2677372Z    9: msim::sim::task::TaskNodeHandle::spawn_local::{{closure}}::{{closure}}
2023-09-12T06:16:20.2678114Z              at /home/runner/.cargo/git/checkouts/tokio-madsim-fork-1ea997b3e6ea1b1d/e469350/tokio/src/macros/select.rs:524:49
2023-09-12T06:16:20.2678728Z   10: <real_tokio::future::poll_fn::PollFn<F> as core::future::future::Future>::poll
2023-09-12T06:16:20.2679466Z              at /home/runner/.cargo/git/checkouts/tokio-madsim-fork-1ea997b3e6ea1b1d/e469350/tokio/src/future/poll_fn.rs:58:9
2023-09-12T06:16:20.2679975Z   11: msim::sim::task::TaskNodeHandle::spawn_local::{{closure}}
2023-09-12T06:16:20.2680603Z              at /home/runner/.cargo/git/checkouts/haneullabs-sim-6c6e892b5d19dc47/03b22b1/msim/src/sim/task.rs:474:17
2023-09-12T06:16:20.2681090Z   12: <core::pin::Pin<P> as core::future::future::Future>::poll
2023-09-12T06:16:20.2681548Z              at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/core/src/future/future.rs:125:9
2023-09-12T06:16:20.2681938Z   13: async_task::raw::RawTask<F,T,S>::run
2023-09-12T06:16:20.2682526Z              at /home/runner/.cargo/git/checkouts/async-task-2c3ead35a682b15c/4e45b26/src/raw.rs:511:20
2023-09-12T06:16:20.2682975Z   14: msim::sim::task::Executor::run_all_ready::{{closure}}
2023-09-12T06:16:20.2683613Z              at /home/runner/.cargo/git/checkouts/haneullabs-sim-6c6e892b5d19dc47/03b22b1/msim/src/sim/task.rs:280:17
2023-09-12T06:16:20.2684039Z   15: std::panicking::try::do_call
2023-09-12T06:16:20.2684451Z      
```

looking into that I've realised that we are attempting to garbage
collect and accept certificates at `gc_round + 1`. However, the way that
we are processing the missing and suspended certificates, it is possible
to have a record at `missing` map for a certificate at `gc_round + 1` -
since some child certificate is missing it - but we have not the actual
certificate it self. So by the time we gc and accept it at `gc_round +
1`, if it's not in the `suspended` map, it will not get processed,
although its children (gc_round + 2) will get released and processed
since their causal history is now satisfied. Thankfully we do have the
parents check in the `accept_certificate_internal` method which won't
allow anything go into the DAG that is above `gc_round + 1` unless we
already have processed its parents , so we do panic and ensure the
consistency of the DAG.

Two ways to fix this:
1. gc up to `gc_round`
2. gc up to `gc_round + 1` , but for the `round = gc_round + 1` missing
elements we do require them to have a corresponding record in the
`suspended` map. Otherwise we skip.

I went with (1) for now for simplicity , but can iterate for (2) as we
might have some slight advantage.


## Test Plan 

How did you test the new or updated feature?

---
If your changes are not user-facing and not a breaking change, you can
skip the following section. Otherwise, please indicate what changed, and
then add to the Release Notes section as highlighted during the release
process.

### Type of Change (Check all that apply)

- [ ] protocol change
- [ ] user-visible impact
- [ ] breaking change for a client SDKs
- [ ] breaking change for FNs (FN binary must upgrade)
- [ ] breaking change for validators or node operators (must upgrade
binaries)
- [ ] breaking change for on-chain data layout
- [ ] necessitate either a data wipe or data migration

### Release notes