Revert "[Build] Remove unused / broken caching steps from Dockerfiles…
## Description
Haneulscan reported an issue
```
...After today's devnet redeploy announcement, we can't run it through docker images. Use the aff8a1cc669b3de79156ed35ead8a64091d406c9 commit to download the image from docker hub.
haneullabs/haneul-node:aff8a1cc669b3de79156ed35ead8a64091d406c9

  Error below:
Creating network "haneul-node_default" with the default driver
Creating volume "haneul-node_haneuldb" with default driver
Creating haneul ... error

ERROR: for haneul  Cannot start service haneul: failed to create shim: OCI runtime create failed: runc create failed: unable to start container process: exec: "/usr/local/bin/haneul-node": stat /usr/local/bin/haneul-node: no such file or directory: unknown

Can you check it please?

We didn't change any configurations, we just updated the image.
```
Reverting https://github.com/GeunhwaJeong/haneul/pull/13049

## Test Plan 
Built the new haneul-node docker image and it worked
```
eugene@mac-studio ~/code/haneul/docker/fullnode (eugene/test_docker_branch) $ docker compose up
[+] Running 6/6
 ✔ fullnode 5 layers [⣿⣿⣿⣿⣿]      0B/0B      Pulled                                                                                                    3.7s
   ✔ 9d21b12d5fab Already exists                                                                                                                       0.0s
   ✔ 84ec7d4e1932 Pull complete                                                                                                                        1.6s
   ✔ a9b442dbdc60 Pull complete                                                                                                                        1.6s
   ✔ b81b15d8848e Pull complete                                                                                                                        1.9s
   ✔ c3a23ea77f15 Pull complete                                                                                                                        2.2s
[+] Running 2/1
 ✔ Container fullnode-fullnode-1                                                                                                                           Recreated0.1s
 ! fullnode The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested 0.0s
Attaching to fullnode-fullnode-1
fullnode-fullnode-1  | 2023-07-24T22:57:55.314277Z  INFO haneul_node: Haneul Node version: 1.6.0-90ccffc02
fullnode-fullnode-1  | 2023-07-24T22:57:55.316885Z  INFO haneul_node: Supported protocol versions: Some(SupportedProtocolVersions { min: ProtocolVersion(1), max: ProtocolVersion(19) })
fullnode-fullnode-1  | 2023-07-24T22:57:55.317822Z  INFO haneul_node: Started Prometheus HTTP endpoint at 0.0.0.0:9184
fullnode-fullnode-1  | 2023-07-24T22:57:55.327446Z  INFO haneul_node: Initializing haneul-node listening on /dns/localhost/tcp/8080/http node=kcd06247d4f1c352af64d56d46306fadbb5fdeaaac71418c37a21273d94e98ddcd6a90917d0417b26d26b04f436018ae0c862a39de3ca5c24ed8cfd6cf7823eaef3262f6408ff877ae5f2fef83511f2678185fe7b770ed4ac787d79a0c153d6e
fullnode-fullnode-1  | 2023-07-24T22:58:30.838945Z  INFO haneul_core::authority::authority_store: Loading epoch start config from DB
fullnode-fullnode-1  | 2023-07-24T22:58:30.848199Z  INFO haneul_core::authority::authority_store: Epoch start config: V2(EpochStartConfigurationV2 { system_state: V1(EpochStartSystemStateV1 { epoch: 0, protocol_version: 9, reference_gas_price: 1000, safe_mode: false, epoch_start_timestamp_ms: 1683583564069, epoch_duration_ms: 86400000, active_validators: [EpochStartValidatorInfoV1 { haneul_address: 0x36df428001ba9645a5fe5dff3af5b94b5bbaae636c8398daf7594a1440bb2d4a, protocol_pubkey: hFJdq3FHjT8OLtgDlx922sG7FsSguhrd54JWv/PEngAjLqZ8GIZ/EYoQUINlIPYVCJZuxXxUnTx2m1OqEj/2ta6qnGZOVb3n8zM0/jKMZaHQw8Hg8MJqNPioOpUoQmdZ, narwhal_network_pubkey: rIBotChaIH7alAxQLYccWLW8GEl+0ZPIIlpI0eTGjPc=, narwhal_worker_pubkey: OL1cSky4WyYDRXAgvH+rtY1gsMM9SDd6MwGPca2ABFQ=, s
...
```