remove some autogenerated lines
## Description 
Fixing:
```
eugene@eugene-dev ~/code/haneul/scripts/compatibility (main) $ ./check-protocol-compatibility.sh mainnet
Found following versions on mainnet:
    175 1.52.2-46fbf847ad8f
     19 1.51.5-2221128f2949
      4 1.52.2-46fbf847ad
      2 1.51.5-2221128f29
      2 1.49.2-2b6aea749cd2
      1 1.50.1-cd131c2366c2
      1 1.48.2-930f160de7c6
      1 1.47.1-8ce91df4f987
      1 1.46.2-3c894a0ab474
      1 1.43.1-02594a24311c

Using most frequent version 1.52.2-46fbf847ad8f for compatibility check
Source commit: 7e313245fb27354513b980ee267d4d727271e12c
Source branch: main
Checking protocol compatibility with mainnet (46fbf847ad8f)
Checking out mainnet snapshot files
Checking for changes to snapshot files matching *__Mainnet_version_*
Error: Detected changes to snapshot files since 46fbf847ad8f - not safe to release
diff --git a/crates/haneul-protocol-config/src/snapshots/haneul_protocol_config__test__Mainnet_version_88.snap b/crates/haneul-protocol-config/src/snapshots/haneul_protocol_config__test__Mainnet_version_88.snap
index 60c6dd64ed..c4d107ddd1 100644
--- a/crates/haneul-protocol-config/src/snapshots/haneul_protocol_config__test__Mainnet_version_88.snap
+++ b/crates/haneul-protocol-config/src/snapshots/haneul_protocol_config__test__Mainnet_version_88.snap
@@ -1,7 +1,6 @@
 ---
 source: crates/haneul-protocol-config/src/lib.rs
 expression: "ProtocolConfig::get_for_version(cur, *chain_id)"
-snapshot_kind: text
 ---
 version: 88
 feature_flags:
 ```

## Test plan 
```
eugene@eugene-dev ~/code/haneul/scripts/compatibility (joy/fix-ci) $
./check-protocol-compatibility.sh mainnet
Found following versions on mainnet:
    175 1.52.2-46fbf847ad8f
     19 1.51.5-2221128f2949
      4 1.52.2-46fbf847ad
      2 1.51.5-2221128f29
      2 1.49.2-2b6aea749cd2
      1 1.50.1-cd131c2366c2
      1 1.48.2-930f160de7c6
      1 1.47.1-8ce91df4f987
      1 1.46.2-3c894a0ab474
      1 1.43.1-02594a24311c

Using most frequent version 1.52.2-46fbf847ad8f for compatibility check
Source commit: 62cd8b0bc61ab272f11d6688cbe2e2400260e466
Source branch: joy/fix-ci
Checking protocol compatibility with mainnet (46fbf847ad8f)
Checking out mainnet snapshot files
Checking for changes to snapshot files matching *__Mainnet_version_*
HEAD is now at 62cd8b0bc6 remove some autogenerated lines
Running snapshot tests...
    Finished `test` profile [unoptimized + debuginfo] target(s) in 0.39s
Running unittests src/lib.rs
(target/debug/deps/haneul_protocol_config-7e53ebf79abab585)

running 1 test
test test::snapshot_tests ... ok

test result: ok. 1 passed; 0 failed; 0 ignored; 0 measured; 5 filtered
out; finished in 0.63s
```