Avoid a spurious assert in tests
This avoids the following crash:

```
thread '<unnamed>' panicked at crates/haneul-core/src/execution_cache/cache_types.rs:307:17:
entry is newer than value 0x86aacc42979583a6797f4bb0cab20d436a1f41e215b2c87cb6e99ffdda5ec7db
stack backtrace:
   0: rust_begin_unwind
             at /rustc/4d91de4e48198da2e33413efdcd9cd2cc0c46688/library/std/src/panicking.rs:692:5
   1: core::panicking::panic_fmt
             at /rustc/4d91de4e48198da2e33413efdcd9cd2cc0c46688/library/core/src/panicking.rs:75:14
   2: haneul_core::execution_cache::cache_types::MonotonicCache<K,V>::insert
             at /Users/jeong-gh/dev/haneul-wb/crates/haneul-core/src/execution_cache/cache_types.rs:307:17
   3: haneul_core::execution_cache::writeback_cache::WritebackCache::cache_latest_object_by_id
             at /Users/jeong-gh/dev/haneul-wb/crates/haneul-core/src/execution_cache/writeback_cache.rs:1210:12
   4: haneul_core::execution_cache::writeback_cache::WritebackCache::cache_object_not_found
             at /Users/jeong-gh/dev/haneul-wb/crates/haneul-core/src/execution_cache/writeback_cache.rs:1224:9
   5: <haneul_core::execution_cache::writeback_cache::WritebackCache as haneul_core::execution_cache::ObjectCacheRead>::find_object_lt_or_eq_version::{{closure}}
   ...
```

The fix is to not overwrite an existing latest cache entry in this
scenario, since it must already be in the correct state at the point at
which the crash was triggered before.