Fix crypto instalation
## Description

I am still hitting this error in the kvstore indexer when the http
client (which is created inside the gcloud sdk) tries to do the Service
Account oath2 flow:

```
2026-01-28T00:48:29.069125Z  INFO haneul_kvstore_alt: Starting haneul-kvstore-alt indexer
  2026-01-28T00:48:29.069142Z  INFO haneul_kvstore_alt: instance_id=kv-load-test-tn-15c12f8
  2026-01-28T00:48:29.069189Z DEBUG provider: gcp_auth: initializing gcp_auth
  2026-01-28T00:48:29.069200Z DEBUG provider: gcp_auth::custom_service_account: check for GOOGLE_APPLICATION_CREDENTIALS env var
  2026-01-28T00:48:29.069208Z DEBUG provider: gcp_auth::types: reading credentials file from GOOGLE_APPLICATION_CREDENTIALS env var path="/secrets/bigtable/bigtable-sa.json"

  thread 'main' (1) panicked at /usr/local/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/rustls-0.23.31/src/crypto/mod.rs:249:14:

  Could not automatically determine the process-level CryptoProvider from Rustls crate features.
  Call CryptoProvider::install_default() before this point to select a provider manually, or make sure exactly one of the 'aws-lc-rs' and 'ring' features is enabled.
  See the documentation of the CryptoProvider type for more information.

  stack backtrace:
  2026-01-28T00:48:29.071933Z ERROR provider: telemetry_subscribers: panicked at /usr/local/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/rustls-0.23.31/src/crypto/mod.rs:249:14:

  Could not automatically determine the process-level CryptoProvider from Rustls crate features.
  Call CryptoProvider::install_default() before this point to select a provider manually, or make sure exactly one of the 'aws-lc-rs' and 'ring' features is enabled.
  See the documentation of the CryptoProvider type for more information.
  panic.file="/usr/local/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/rustls-0.23.31/src/crypto/mod.rs" panic.line=249 panic.column=14
  0:     0x593514e249d2 - <std::sys::backtrace::BacktraceLock::print::DisplayBacktrace as core::fmt::Display>::fmt::h718e2d17a1928e63
  1:     0x593514e37e2f - core::fmt::write::h1d2246b072ea91eb
  2:     0x593514dee433 - std::io::Write::write_fmt::haf55272405c09d9b
  3:     0x593514dfc052 - std::sys::backtrace::BacktraceLock::print::h61c3bd81a9458a03
  4:     0x593514e01a4c - std::panicking::default_hook::{{closure}}::haf1ffb5d1e33a97f
  5:     0x593514e018a6 - std::panicking::default_hook::hc32245deb6eaa988
  6:     0x5935142440d9 - telemetry_subscribers::set_panic_hook::{{closure}}::ha05f15ea0276e5f5
  7:     0x593514e0210f - std::panicking::panic_with_hook::h43adc00fd0e494cb
  8:     0x593514e01eba - std::panicking::panic_handler::{{closure}}::h44391079756da3e7
  9:     0x593514dfc199 - std::sys::backtrace::__rust_end_short_backtrace::h934e1568393e5b8f
  10:     0x593514de18bd - __rustc[d9b87f19e823c0ef]::rust_begin_unwind
  11:     0x593514e42e70 - core::panicking::panic_fmt::h62031895f6e012da
  12:     0x593514e41f2b - core::option::expect_failed::h40dde8b63ee0f843
  13:     0x593514bb8ca2 - rustls::client::client_conn::ClientConfig::builder_with_protocol_versions::h60f9ded0f3cae764
  14:     0x593514bb8d16 - rustls::client::client_conn::ClientConfig::builder::h7811672c3eb7955a
  15:     0x5935149721bd - hyper_rustls::connector::builder::ConnectorBuilder<hyper_rustls::connector::builder::WantsTlsConfig>::with_native_roots::hed85eeb9ba0d71bb
  16:     0x59351446ce92 - gcp_auth::types::HttpClient::new::h6990ae7b90c1141c
  17:     0x59351447f56d - gcp_auth::custom_service_account::CustomServiceAccount::from_env::h7fe855f92174b3ce
  18:     0x5935141de1f7 - <tracing::instrument::Instrumented<T> as core::future::future::Future>::poll::he5a60383e11f9830
  19:     0x5935141870e7 - haneul_kvstore_alt::main::{{closure}}::h1dc6d93a588f0095
  20:     0x59351419a179 - tokio::runtime::park::CachedParkThread::block_on::h97f30430cd7e806a
  21:     0x593514129423 - tokio::runtime::context::runtime::enter_runtime::hd90b73dfe83d7f73
  22:     0x593514231755 - tokio::runtime::runtime::Runtime::block_on::h1aa9ae7b26e0cf20
  23:     0x593514185d67 - haneul_kvstore_alt::main::h38ced8ef6f224aa0
  24:     0x5935141f08d3 - std::sys::backtrace::__rust_begin_short_backtrace::h04a5150d6b89a5f3
  25:     0x5935141b7bbd - std::rt::lang_start::{{closure}}::h4a59f6a0be951b3b
  26:     0x593514df0310 - std::rt::lang_start_internal::h00c7908c7c2f92b8
  27:     0x5935141a77dc - main
  28:     0x7a61acbd624a - <unknown>
  29:     0x7a61acbd6305 - __libc_start_main
  30:     0x593513fc3c2a - _start
  31:                0x0 - <unknown>
```

This feature configuration is working and should fix this problem
workspace wide. I think the only other options would be fixing it with
the install_default() call in the main method (for binary crates where
we don't control http client construction), or somehow working around
the gcloud SDK and writing our own auth flow. As far as I can tell there
is no way to pass your own tls provider into the sdk.